### ISSUE TITLE
test failure on 32bit systems: error: invalid zip file with overlapped components (possible zip bomb)

### ISSUE THREAD

**Issue by Whissi** [madler/unzip#2] opened 2019-10-28 00:08 UTC
Hi,

on Gentoo x86, unzip test suite is failing with
```
#####  testing unzipsfx (self-extractor)
UnZipSFX 6.00 of 20 April 2009, by Info-ZIP (http://www.info-zip.org).
error: invalid zip file with overlapped components (possible zip bomb)
make: *** [Makefile:501: check] Error 12
```
I tested this git repository, too. Same failure.

Gentoo Bug report with complete build.log: https://bugs.gentoo.org/698694

**Comment by DerDakon** [comment] 2019-10-30 20:30
It does the same on hppa (32 bit, big endian).

**Comment by DarthGandalf** [comment] 2019-11-03 21:28
Same on 32 bit arm.

**Comment by madler** [comment] 2020-02-09 02:23
I was not able to duplicate the unzipsfx failure on a 32-bit Debian system.

**Comment by madler** [comment] 2020-02-09 04:31
I _was_ able to duplicate the failure. I needed to turn on `ZIP64_SUPPORT`. Will investigate ...

**Comment by madler** [comment] 2020-02-09 16:08
Should be fixed by https://github.com/madler/unzip/commit/13f0260beae851f7d5dd96e9ef757d8d6d7daac1 .

**Closed by madler** 2020-02-09 16:08 UTC

**Comment by bmenrigh** [comment] 2021-03-24 23:51
There may be more here that needs fixing besides the https://github.com/madler/unzip/commit/13f0260beae851f7d5dd96e9ef757d8d6d7daac1 commit.

On a RHEL system I was getting `error: invalid zip file with overlapped components (possible zip bomb)` immediately. I cloned this repo and built from source. This version got much deeper into the zip before reporting the same issue.

So I manually patched out the zip bomb detection by commenting out the three `OverlappedComponents` related `if` statements in `extract.c` that return `PK_BOMB`. This patched version was able to extract the zip without any issue.

Here is what unzip -v reports:
```
$ ~/unzip/unzip -v namemasked_files.zip 
Archive:  namemasked_files.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     333  Defl:N      338  -2% 03-23-2021 16:17 202caaf2  namemasked-000001.vmdk
      91  Defl:N       96  -6% 03-23-2021 16:17 9d4b028a  namemasked-4c84ca7a.hlog
8603656912  Defl:N 8604969722   0% 03-23-2021 16:17 b49e5be9  namemasked-Snapshot1.vmsn
    8684  Defl:N     8689  -0% 03-23-2021 16:22 add3514c  namemasked.nvram
     554  Defl:N      559  -1% 03-23-2021 16:22 a9c9b283  namemasked.vmdk
10737418240  Defl:N 10739056640   0% 03-23-2021 16:22 ffbba3f7  namemasked-flat.vmdk
     656  Defl:N      661  -1% 03-23-2021 16:27 e658885f  namemasked.vmsd
    4030  Defl:N     4035  -0% 03-23-2021 16:27 69a89a64  namemasked.vmx
     337  Defl:N      342  -2% 03-23-2021 16:27 edd8acda  namemasked_1-000001.vmdk
     556  Defl:N      561  -1% 03-23-2021 16:27 5c597973  namemasked_1.vmdk
26843545600  Defl:N 26847641600   0% 03-23-2021 16:27 b449803b  namemasked_1-flat.vmdk
     337  Defl:N      342  -2% 03-23-2021 16:40 cc17b15c  namemasked_2-000001.vmdk
     556  Defl:N      561  -1% 03-23-2021 16:40 e42bd0db  namemasked_2.vmdk
10737418240  Defl:N 10739056640   0% 03-23-2021 16:40 40320bb1  namemasked_2-flat.vmdk
  261577  Defl:N   261612   0% 03-23-2021 16:46 f5a2d19a  vmware-91.log
  261740  Defl:N   261775   0% 03-23-2021 16:46 1c2256b7  vmware-92.log
  261753  Defl:N   261788   0% 03-23-2021 16:46 0e98e815  vmware-93.log
  290453  Defl:N   290493   0% 03-23-2021 16:46 9a73c82e  vmware-94.log
  506819  Defl:N   506894   0% 03-23-2021 16:46 4cbe76c7  vmware-95.log
  307366  Defl:N   307411   0% 03-23-2021 16:46 14661863  vmware-96.log
  287300  Defl:N   287340   0% 03-23-2021 16:46 fc1591bd  vmware.log
    2195  Defl:N     2200  -0% 03-23-2021 16:46 0de0d743  Error report.log
--------          -------  ---                            -------
56924234329         56932920299   0%                            22 files
```

I don't know what zip software was used to create the zip and I'm not certain that it doesn't actually contain overlapping components. I do know however that it wasn't maliciously constructed and it does extract without error (presumably passing the CRC- checks) when I patched out the zip bomb detection.

**Comment by madler** [comment] 2021-03-25 00:02
Though this is an extremely large file, can you make it available for me to download?

**Comment by bmenrigh** [comment] 2021-03-25 00:29
> Though this is an extremely large file, can you make it available for me to download?

I'm sorry I can't. It's a forensic disk image and contains sensitive data. This is in part why I masked the name and provided the -v output.

I'd be willing to test various patches though. For example, if you made a debugging patch that reported component offsets and such I'd be wiling to run that and give you the log. I know this isn't an ideal option.

**Comment by pmqs** [comment] 2021-03-25 09:22
I have a script, called `zipdetails`,  that will dump data about the internal structure of zip files. Recently I've adding logic to detect zipbomb/overlapping entries. Rather than exiting at the first sign of a bad entry it attempts to log what the problem is and continue.

The zipbomb detection is still a work in progress, but it should allow you to share data about the structure of your zip file without having to publish the full zip file.

Given the sensitive data you are working with, I added a `redact` option to mask out the filenames in the output. 

The script has been uploaded to https://gist.github.com/pmqs/fddfe85246e99d8d3764bd1f1cb2d58f

Run it like so

`$ perl zipdetails -v -redact yourfile.zip`


If you are happy that this doesn't output any sensitive data, can you post it here?

**Comment by bmenrigh** [comment] 2021-03-25 21:09
I am sufficiently pleased with the redacted output, thank you for adding it. The output is attached. Note that the overlap detection is causing the script to exit with a die on line 2328 in the save() subroutine. I modified the script and changed that die to a warn in hopes of collecting more data.

For whatever reason GitHub is not allowing me to attach the files to this post. I have uploaded them to
http://www.brandonenright.net/~bmenrigh/zipdetails.txt and http://www.brandonenright.net/~bmenrigh/zipdetails_warn.txt

**Comment by madler** [comment] 2021-03-25 22:10
Thanks Paul!

**Comment by pmqs** [comment] 2021-03-25 22:47
> I am sufficiently pleased with the redacted output, thank you for adding it. The output is attached. Note that the overlap detection is causing the script to exit with a die on line 2328 in the save() subroutine. I modified the script and changed that die to a warn in hopes of collecting more data.

That `die` should be a `print`. I did say this is a work in progress :-)

> For whatever reason GitHub is not allowing me to attach the files to this post. I have uploaded them to
> http://www.brandonenright.net/~bmenrigh/zipdetails.txt and http://www.brandonenright.net/~bmenrigh/zipdetails_warn.txt

Getting late here, but the first problem I see, apart from all the apparent overlaps the script is reporting, is a discrepancy in the length of the third entry. In the local header it is listed as `00E56AFA` compressed bytes, but the central directory equivalent lists it as `200E56AFA` bytes. Looks like the local entry has been written as a 32-bit value. The central directory suggests it is a 64-bit value.

Given that my script cannot find the fourth local header it suggests the central header length is incorrect.

In order to see which is true, can you run my script again with the `--scan` option. This changes the way the script scan the file. With a bit of luck it will show us all the local headers.

The `--scan` option may take a while to run, so just let it cook.

**Comment by pmqs** [comment] 2021-03-25 22:48
> Thanks Paul!

You're welcome.

**Comment by bmenrigh** [comment] 2021-03-26 01:04
> Getting late here, but the first problem I see, apart from all the apparent overlaps the script is reporting, is a discrepancy in the length of the third entry. In the local header it is listed as `00E56AFA` compressed bytes, but the central directory equivalent lists it as `200E56AFA` bytes. Looks like the local entry has been written as a 32-bit value. The central directory suggests it is a 64-bit value.

It's entirely possible that whatever software was used to create this zip is partially broken. If so, it's a miracle that unzip was able to extract it once I patched out the overlap detection. Would it help if I tracked down the person that made this zip and got the exact software version info? I'm not entirely sure I even can track down the creator since getting this image involved multiple layers of delegation from team to team, spanning multiple timezones. I'm willing to try though.

> 
> Given that my script cannot find the fourth local header it suggests the central header length is incorrect.
> 
> In order to see which is true, can you run my script again with the `--scan` option. This changes the way the script scan the file. With a bit of luck it will show us all the local headers.
> 
> The `--scan` option may take a while to run, so just let it cook.

The scan option doesn't look to be an option. It is spitting out large sections of unredacted filesystem content listed as "comments". It's also outputting huge chunks of XX...XXX for impossibly long filenames. If I had to guess, I'd say the pattern that --scan looks for can false-positive quite frequently where the size of the "comment" / "filename" can be quite large.  I ran --scan for a few minutes and it had already output more than 5GB of data (as measured by piping the output to dd of=/dev/null).

If this is a matter of which header size/offset offset is correct, perhaps instead you can give me a few offsets into the file where I can provide a manually redacted (if needed) hexdump?

Maybe I'm getting into crazy territory here, but perhaps your zipdetails script could be made to backtrack and try different offsets when it fails to find the expected header?  If this is a matter of truncating a 64-bit size into a 32-bit field (`200E56AFA` -> `00E56AFA`) then perhaps a middle-ground between a full --scan would be to try the 16 offsets {X}00E56AFA in turn and backtrack when there isn't the expected header at each one of those.

I do **greatly** appreciate both of your support here. Thanks to both of you for your willingness to troubleshoot my (likely) broken zip file.

**Comment by madler** [comment] 2021-03-26 03:56
> Getting late here, but the first problem I see, apart from all the apparent overlaps the script is reporting, is a discrepancy in the length of the third entry. In the local header it is listed as `00E56AFA` compressed bytes, but the central directory equivalent lists it as `200E56AFA` bytes. Looks like the local entry has been written as a 32-bit value. The central directory suggests it is a 64-bit value.

It looks right to me, since the next four bytes are 02 00 00 00. Your script may be incorrectly interpreting that data descriptor as having four-byte lengths when in fact it has eight-byte lengths. In fact, the central header for that entry has a Zip64 extra field, which, according to the appnote, requires that the data descriptor have eight-byte lengths.

**Comment by madler** [comment] 2021-03-26 06:04
The central directory indicates that there is, correctly, 24 bytes for the data descriptor at the end of entry #3. The first problem occurs at the end of entry #4.

Entry #4 has only ten bytes for the data descriptor. The central directory has a Zip64 extended information extra field, so per section 4.3.9.2 of the PKWare APPNOTE, the compressed and uncompressed sizes must be eight bytes each. Regardless of whether you need eight bytes to represent them. It is the offset of the local header, not the sizes, that force the long data descriptor.

This occurs consistently for all files that are small, but start after the first 4 GB of the zip file. The problem is not there for files that have lengths that require eight bytes to represent them.

I can see how the author of the code might assume that the data descriptor would only use four-byte values for short lengths. But unfortunately that is incorrect.

**Comment by pmqs** [comment] 2021-03-26 12:24
> > Getting late here, but the first problem I see, apart from all the apparent overlaps the script is reporting, is a discrepancy in the length of the third entry. In the local header it is listed as `00E56AFA` compressed bytes, but the central directory equivalent lists it as `200E56AFA` bytes. Looks like the local entry has been written as a 32-bit value. The central directory suggests it is a 64-bit value.
> 
> It looks right to me, since the next four bytes are 02 00 00 00. Your script may be incorrectly interpreting that data descriptor as having four-byte lengths when in fact it has eight-byte lengths. In fact, the central header for that entry has a Zip64 extra field, which, according to the appnote, requires that the data descriptor have eight-byte lengths.

Yep, you are correct. It looks like the central directory for #3 says the file is 64 bit, but the equivalent local header doesn't have the zip64 extra field present, but does have a 64-bit data descriptor.  So it is inconsistent. 

My script takes each directory entry at face value when decoding, so tries to decode the inconsistent local entry in 32 bit mode. 

I'll update my code to assume that the central directory holds the truth

**Comment by pmqs** [comment] 2021-03-26 12:45
> > Getting late here, but the first problem I see, apart from all the apparent overlaps the script is reporting, is a discrepancy in the length of the third entry. In the local header it is listed as `00E56AFA` compressed bytes, but the central directory equivalent lists it as `200E56AFA` bytes. Looks like the local entry has been written as a 32-bit value. The central directory suggests it is a 64-bit value.
> 
> It's entirely possible that whatever software was used to create this zip is partially broken. If so, it's a miracle that unzip was able to extract it once I patched out the overlap detection. Would it help if I tracked down the person that made this zip and got the exact software version info? I'm not entirely sure I even can track down the creator since getting this image involved multiple layers of delegation from team to team, spanning multiple timezones. I'm willing to try though.

It would be good to know what tools was used to create the zip file.

> 
> > Given that my script cannot find the fourth local header it suggests the central header length is incorrect.
> > In order to see which is true, can you run my script again with the `--scan` option. This changes the way the script scan the file. With a bit of luck it will show us all the local headers.
> > The `--scan` option may take a while to run, so just let it cook.
> 
> The scan option doesn't look to be an option. It is spitting out large sections of unredacted filesystem content listed as "comments". It's also outputting huge chunks of XX...XXX for impossibly long filenames. If I had to guess, I'd say the pattern that --scan looks for can false-positive quite frequently where the size of the "comment" / "filename" can be quite large. I ran --scan for a few minutes and it had already output more than 5GB of data (as measured by piping the output to dd of=/dev/null).
> 
> If this is a matter of which header size/offset offset is correct, perhaps instead you can give me a few offsets into the file where I can provide a manually redacted (if needed) hexdump?
> 
> Maybe I'm getting into crazy territory here, but perhaps your zipdetails script could be made to backtrack and try different offsets when it fails to find the expected header? If this is a matter of truncating a 64-bit size into a 32-bit field (`200E56AFA` -> `00E56AFA`) then perhaps a middle-ground between a full --scan would be to try the 16 offsets {X}00E56AFA in turn and backtrack when there isn't the expected header at each one of those.

The `scan` option is supposed to try _really_ hard to find anything that looks like a zip directory entry - it just starts at the beginning of the file and reads evry byte in the file until it finds a directory signature. Then it decodes that entry and scans again. The problem with it is false positives - if the compressed data in the zip file happens to have a four byte sequence that matches one of the zip directory headers it will blindly try to decode it. I suspect that is what you are tripping over.

I'm fixing the script to deal with the Zip64 inconsistency between the central and local headers. Means you won't have to run with the `scan` option. Should have something today to try out. Hopefully that will allow us to get a full picture of the structure of your zip file.

**Comment by pmqs** [comment] 2021-03-26 16:20
@bmenrigh new version of the script available https://github.com/pmqs/zipdetails/blob/main/bin/zipdetails (note this is a new location)

The change should hopefully cope with the mismatch between the central & local headers.

Usage is

`$ perl zipdetails -v -redact yourfile.zip`

**Comment by madler** [comment] 2021-03-26 16:49
> It would be good to know what tools was used to create the zip file.

I'm going to guess Java's ZipOutputStream. I think I've seen this before.

**Comment by bmenrigh** [comment] 2021-03-26 17:41
I have run Paul's updated script. The output is looking good.

http://www.brandonenright.net/~bmenrigh/zipdetails_new_2021032617.txt

I'm working on getting details about the library used to make this zip. I likely won't know until next week.

**Comment by pmqs** [comment] 2021-03-26 22:30
Damn! The data is getting truncated after local header `#4` . I see the problem with my code. Hopefully sorted  - new version available at https://github.com/pmqs/zipdetails/blob/main/bin/zipdetails . Can you give it a go if you get a chance please?

**Comment by bmenrigh** [comment] 2021-03-27 00:10
> Damn! The data is getting truncated after local header `#4` . I see the problem with my code. Hopefully sorted - new version available at https://github.com/pmqs/zipdetails/blob/main/bin/zipdetails . Can you give it a go if you get a chance please?

Absolutely! The new script gives substantially more output:

http://www.brandonenright.net/~bmenrigh/zipdetails_new_2021032700.txt

**Comment by pmqs** [comment] 2021-03-28 21:37
I've had a closer look at the latest output. The only issue I see is with `#3` where it is missing a Zip64 extra field.

I created a zip file >4Gig locally with the missing Zip64 extra field, but unzip doesn't complain about it.

Mark - would a missing a Zip64 extra field be enough to trigger an `overlapped components` error in unzip? 

Brandon - another version of my script is available at https://github.com/pmqs/zipdetails/blob/main/bin/zipdetails. This one has better (but not exhaustive) overlap detection in place. It should also explicitly report the missing zip64 field. Can you give it a go please?

Also, regarding the source of the file - do you think is it possible to get an example file that `unzip` doesn't like that can be shared?

**Comment by madler** [comment] 2021-03-29 02:14
There is no issue with entry #3. As I said above, the first problem is in entry #4. Entry #3 does indeed have a Zip64 extra field in the central header.

Entry #4 has a Zip64 extra field in the central header, so it's data descriptor is supposed to have eight-byte lengths. A data descriptor of that length then overlaps the start of local header #5 by eight bytes.

**Comment by pmqs** [comment] 2021-03-29 16:14
> There is no issue with entry #3. 

Correct. There is an inconsistency in `#3` between the local & central header that isn't relevant here - just means that a streaming unzip, that relies on the accuracy of the local headers, will have problems.

> Entry #4 has a Zip64 extra field in the central header, so its data descriptor is supposed to have eight-byte lengths. A data descriptor of that length then overlaps the start of local header #5 by eight bytes.

The zipbomb logic appears to be in a grey(ish) area. There is an assumption that the data descriptor needs to include 8 byte sizes because the central directory has a Zip64 entry. That sounds fine, when there is a well-formed Zip64 entry in the central directory. In this case the Zip64 entry doesn't contain any size data, so doesn't conform to 4.3.9.2. The code is making an assumption based on a well-formed Zip64 entry in the central directory that doesn't exist.

This use case isn't malicious, so is there case for modifying the zipbomb logic to deal with this edge condition? Before zipbomb logic was added, unzip could infer the intent with this type of file and unzip it.

**Comment by bmenrigh** [comment] 2021-03-29 22:47
I'm sorry for the delay in my response. Multiple other emergencies kept grabbing my attention.

> Brandon - another version of my script is available at https://github.com/pmqs/zipdetails/blob/main/bin/zipdetails. This one has better (but not exhaustive) overlap detection in place. It should also explicitly report the missing zip64 field. Can you give it a go please?

It sounds like the problem is pretty well understood now but in case it helps here is the output from latest version of your tool:

http://www.brandonenright.net/~bmenrigh/zipdetails_new_2021032917.txt

> Also, regarding the source of the file - do you think is it possible to get an example file that `unzip` doesn't like that can be shared?

I haven't yet tracked down the person or the software that made this zip. Even when I do I doubt I'll be able to get them to zip up a few large benign files for me in the hopes that it's similarly malformed.

I get the impression though that your zipdetails script isn't too far away from being able to construct a 'redacted' zip that matches the exact structure of an existing zip. Bytes could be copied from the source to the redacted destination, replacing filenames with something like your X...X and (probably?) replacing the deflate/compression stream with some sort of dummy data. I suppose this would be hard to do generically for all different datastream types.  I guess it would also be hard in the case where the zip is so malformed that the zipdetails script can't even figure out what bytes are filename and which are compression stream and so on.

It's been frustrating to me that I haven't been able to help more and provide a copy of the zip I have.  If I had a way of redacting the zip or reproducing with benign data so that i could share a useful malformed sample I would.

**Comment by madler** [comment] 2021-03-29 23:27
> Correct. There is an inconsistency in `#3` between the local & central header that isn't relevant here - just means that a streaming unzip, that relies on the accuracy of the local headers, will have problems.

It is not required for a local header to contain the same extra blocks as the central header, and in fact it is not possible for a streaming zipper. The zipper does not know at the time the local header is written what the lengths and CRC will be, which is exactly why there is such a thing as a data descriptor after the compressed data. The information needed to populate a Zip64 extra block does not exist at the time the local header is written, so there can't be one there. (Similarly, those fields in the local header are set to zero.) The Zip64 extra block can only be in the corresponding central header. It must be there if any of the lengths, offset, or disk number don't fit in their respective slots in the usual central header.

So there is no "inconsistency" that I see.

While the zip format was designed to support streaming zippers, it was not designed to support streaming unzippers. Nevertheless my streaming unzipper sunzip has no problem with this, resolving any ambiguities at the time the data descriptor is encountered, which includes most annoyingly whether the data descriptor signature is present or not.

Nor is it a problem for a streaming zipper, since at the time the data descriptor is written the offset, disk, and lengths are known, so it is known whether there will need to be a Zip64 extra block in the central directory. Or the code could elect to always put a Zip64 extra block in the central directory (permitted by the appnote), in which case the code knows that it will be doing that at the time the data descriptor is written, and use eight-byte lengths.

> The zipbomb logic appears to be in a grey(ish) area. There is an assumption that the data descriptor needs to include 8 byte sizes because the central directory has a Zip64 entry. That sounds fine, when there is a well-formed Zip64 entry in the central directory. In this case the Zip64 entry doesn't contain any size data, so doesn't conform to 4.3.9.2. The code is making an assumption based on a well-formed Zip64 entry in the central directory that doesn't exist.

It is not a gray area with respect to the appnote, which is clear, and 4.3.9.2 says nothing about the Zip64 entry containing size data. It says that if there is a Zip64 extra field present for the entry, then the _data descriptor_  must have eight-byte lengths. The Zip64 extra field that is there is well-formed, compliant, and required. It is required because the offset doesn't fit in 32 bits. It is compliant because that is the only value doesn't fit in its field, and the offset is the only one marked with all one bits in the header.

> This use case isn't malicious, so is there case for modifying the zipbomb logic to deal with this edge condition? Before zipbomb logic was added, unzip could infer the intent with this type of file and unzip it.

I will look at making this a different warning and proceeding, using the same logic sunzip does to permit all four possibilities of signature/no signature, four-byte/eight-byte lengths. The zip bomb detection in unzip turns out to be a good at also detecting bugs in zip files, so I do not plan to completely silence it.

**Comment by madler** [comment] 2021-03-30 04:15
> Also, regarding the source of the file - do you think is it possible to get an example file that `unzip` doesn't like that can be shared?

This Java code will generate such a zip file on stdout:

```
// Generate a large, malformed zip file using Java's ZipOutputStream.

import java.io.*;
import java.util.zip.*;
import java.util.Random;

class malzip {
    public static void main(String[] args) {
        byte[] buf = new byte[65536];
        Random gen = new Random(1);
        gen.nextBytes(buf);
        ZipOutputStream zip = new ZipOutputStream(new BufferedOutputStream(System.out));
        try {
			zip.putNextEntry(new ZipEntry("foo"));
			for (int i = 0; i < 65517; i++)
				zip.write(buf);
			zip.closeEntry();
			zip.putNextEntry(new ZipEntry("bar"));
			zip.write("123456789".getBytes());
			zip.close();
        }
        catch (IOException e) {
            System.err.println("I/O error writing zip file");
        }
    }
}

```

It has exactly the same problem seen in Brandon's zip file, which is why I suspect that Java's `ZipOutputStream` was the source.

I arranged the data so that the result is significantly compressible by xz. It is a 4,295,032,214 byte .zip file, but compresses by xz to 1,996,052 bytes, making it much more amenable to downloading. [Click to download mal.zip.xz](http://zlib.net/exchange/mal.zip.xz). When you decompress with xz, you'll get the result of the Java program as mal.zip.

**Comment by pmqs** [comment] 2021-03-30 07:32
> I'm sorry for the delay in my response. Multiple other emergencies kept grabbing my attention.
> 
> > Brandon - another version of my script is available at https://github.com/pmqs/zipdetails/blob/main/bin/zipdetails. This one has better (but not exhaustive) overlap detection in place. It should also explicitly report the missing zip64 field. Can you give it a go please?
> 
> It sounds like the problem is pretty well understood now but in case it helps here is the output from latest version of your tool:
> 
> http://www.brandonenright.net/~bmenrigh/zipdetails_new_2021032917.txt

Thanks

> > Also, regarding the source of the file - do you think is it possible to get an example file that `unzip` doesn't like that can be shared?
> 
> I haven't yet tracked down the person or the software that made this zip. Even when I do I doubt I'll be able to get them to zip up a few large benign files for me in the hopes that it's similarly malformed.
> 
> I get the impression though that your zipdetails script isn't too far away from being able to construct a 'redacted' zip that matches the exact structure of an existing zip. Bytes could be copied from the source to the redacted destination, replacing filenames with something like your X...X and (probably?) replacing the deflate/compression stream with some sort of dummy data. I suppose this would be hard to do generically for all different datastream types. I guess it would also be hard in the case where the zip is so malformed that the zipdetails script can't even figure out what bytes are filename and which are compression stream and so on.

Yes,  Mark have created an example zip file that triggers the issue, so no need to get a sample.  Java code that is likely the culprit in this case.

**Comment by pmqs** [comment] 2021-03-30 08:41
> I will look at making this a different warning and proceeding, using the same logic sunzip does to permit all four possibilities of signature/no signature, four-byte/eight-byte lengths. The zip bomb detection in unzip turns out to be good at also detecting bugs in zip files, so I do not plan to completely silence it.

Excellent!

**Comment by pmqs** [comment] 2021-03-30 08:51
> I arranged the data so that the result is significantly compressible by xz. It is a 4,295,032,214 byte .zip file, but compresses by xz to 1,996,052 bytes, making it much more amenable to downloading. [Click to download mal.zip.xz](http://zlib.net/exchange/mal.zip.xz). When you decompress with xz, you'll get the result of the above Java program as mal.zip.

That's nothing! I've contrived an example file that compresses a zip file from 4,294,967,639 to 342 bytes! The trick I used was to store create the payload data as a sparse file. Means the only real data in the file is the zip headers. Limitation, of course, is the payload data is Stored and can only contain null bytes.
